package io.github.sam42r.reindeer.view;

import com.flowingcode.vaadin.addons.chatassistant.ChatAssistant;
import com.flowingcode.vaadin.addons.chatassistant.model.Message;
import com.vaadin.flow.component.Unit;
import com.vaadin.flow.component.avatar.Avatar;
import com.vaadin.flow.component.html.IFrame;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.PreserveOnRefresh;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.server.streams.DownloadHandler;
import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;

import java.time.LocalDateTime;

@Slf4j
@Route("overlay")
@PreserveOnRefresh
//@Theme(variant = Lumo.DARK)
public class AgentOverlay extends VerticalLayout {

    public AgentOverlay() {
        var chatAssistant = new ChatAssistant<>();
        chatAssistant.setAvatarProvider(this::avatar);

        chatAssistant.sendMessage(Message.builder().content("Hello, I am here to assist you")
                .messageTime(LocalDateTime.now())
                .name("Assistant").avatar("chatbot.png")
                //.tagline("Generated by assistant")
                .loading(true)
                .build());
        chatAssistant.setUnreadMessages(1);

        var iframe = new IFrame("https://gitmoji.dev/");
        iframe.setWidth(100, Unit.PERCENTAGE);
        iframe.setHeight(100, Unit.VH);
        iframe.getStyle().setBorder("none");

        setSizeFull();
        setPadding(false);
        setSpacing(false);
        add(iframe, chatAssistant);
    }

    @SneakyThrows
    private Avatar avatar() {
        var avatar = new Avatar();
        avatar.setImageHandler(DownloadHandler.forClassResource(AgentOverlay.class, "/chatbot.png"));
        avatar.setColorIndex(0);
        avatar.setName("Eva");

        return avatar;
    }
}
